In [1]:
#2. read the HTML file as given below

import numpy as np
import pandas as pd

url= "http://vincentarelbundock.github.io/Rdatasets/datasets.html"
HTMLData = pd.read_html(url, header =0)
print(type(HTMLData))

# create a data frame from the above object
HTMLDataFrame = pd.DataFrame(HTMLData[1])
print(type(HTMLDataFrame))

HTMLDataFrame.head() # Printing the top 5 rows

<class 'list'>
<class 'pandas.core.frame.DataFrame'>

,Package,Item,Title,Rows,Cols,CSV,Doc
0,boot,acme,Monthly Excess Returns,60,3,CSV,DOC
1,boot,aids,Delay in AIDS Reporting in England and Wales,570,6,CSV,DOC
2,boot,aircondit,Failures of Air-conditioning Equipment,12,1,CSV,DOC
3,boot,aircondit7,Failures of Air-conditioning Equipment,24,1,CSV,DOC
4,boot,amis,Car Speeding and Warning Signs,8437,4,CSV,DOC